# COLUMN NAMES
COLUMN_TEXT_ID = 'text_id'
COLUMN_TEXT = 'text'
COLUMN_TEXT_LEVEL = 'text_level'
COLUMN_QUESTION_ID = 'question_id'
COLUMN_QUESTION = 'question'
COLUMN_OPTIONS = 'options'
COLUMN_OPTION_A = 'option_a'
COLUMN_OPTION_B = 'option_b'
COLUMN_OPTION_C = 'option_c'
COLUMN_OPTION_D = 'option_d'
COLUMN_CORRECT_ANSWER = 'correct_answer'
COLUMN_QUESTION_DIFFICULTY = 'question_difficulty'

COLUMN_NAMES = [
    COLUMN_TEXT_ID,
    COLUMN_TEXT,
    COLUMN_TEXT_LEVEL,
    COLUMN_QUESTION_ID,
    COLUMN_QUESTION,
    COLUMN_OPTIONS,
    COLUMN_OPTION_A,
    COLUMN_OPTION_B,
    COLUMN_OPTION_C,
    COLUMN_OPTION_D,
    COLUMN_CORRECT_ANSWER,
    COLUMN_QUESTION_DIFFICULTY,
]
